id: A22A3ABBA
title: Prayer to the Gurus of the Dzogchen Lineage
type: translation
pechas:
- I7EAE4030
- IE00493A9
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:42:26.615602
  last_modified_at: 2023-01-04 11:42:26.615613
  collections:
  - Dodrupchen Jigme Tenpe Nyima Series
  - Works of Tibetan Masters
alignment_to_base:
  I7EAE4030/CE2F: 64EC
  IE00493A9/6966: 64EC
